version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/backend/V.T.Thanh-Home-SpringBoot"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 10
    groups:
      spring-minor-patch:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    assignees:
      - "JuniorThanhBQ"
    reviewers:
      - "JuniorThanhBQ"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/frontend/V.T.Thanh-Home-Angular"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 10
    groups:
      angular-minor-patch:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    assignees:
      - "JuniorThanhBQ"
    reviewers:
      - "JuniorThanhBQ"
    labels:
      - "dependencies"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Ho_Chi_Minh"
    assignees:
      - "JuniorThanhBQ"
    reviewers:
      - "JuniorThanhBQ"
    labels:
      - "dependencies"
