fail_fast: false
default_stages: [pre-commit, pre-merge-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ["--maxkb=3096"]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-yaml
        exclude: ^(\.github/|frontend/|backend/)
      - id: check-json
        exclude: (?i)(\.vscode/|tsconfig.*\.json|angular\.json)
      - id: check-xml
      - id: detect-private-key

  - repo: local
    hooks:
      - id: prettier
        name: Prettier local for Angular
        language: system
        entry: npm --prefix frontend/V.T.Thanh-Home-Angular exec prettier -- --write "."
        files: ^frontend/
        types_or:
          [javascript, jsx, ts, tsx, html, css, scss, json, yaml, markdown]
        exclude: |
          (?x)^(
            frontend/package-lock\.json|
            frontend/.*\.min\..*|
            frontend/V\.T\.Thanh-Home-Angular/package-lock\.json
          )$

      - id: ng-lint
        name: Angular ESLint
        language: system
        entry: npm --prefix frontend/V.T.Thanh-Home-Angular run lint
        files: ^frontend/V\.T\.Thanh-Home-Angular/src/.*\.(ts|html)$
        pass_filenames: false

  - repo: local
    hooks:
      - id: gradle-spotless
        name: gradle spotless check
        entry: cmd /c "cd backend\V.T.Thanh-Home-SpringBoot && gradlew.bat spotlessCheck"
        language: system
        files: ^backend/V\.T\.Thanh-Home-SpringBoot/.*\.java$
        pass_filenames: false

      - id: gradle-checkstyle
        name: Gradle Checkstyle
        entry: cmd /c "cd backend\V.T.Thanh-Home-SpringBoot && gradlew.bat checkstyleMain"
        language: system
        files: ^backend/V\.T\.Thanh-Home-SpringBoot/src/main/java/.*\.java$
        pass_filenames: false

  - repo: https://github.com/hadolint/hadolint
    rev: v2.15.1
    hooks:
      - id: hadolint-docker
        name: Hadolint Dockerfile Linter
        types: [dockerfile]

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.30.1
    hooks:
      - id: zizmor
        args: [--no-progress, --fix=safe]
