[project]
name = "v-t-thanh-home"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Van Trung Thanh", email = "thanh.vantrung2005@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "requests>=2.34.2",
]

[project.scripts]
v-t-thanh-home = "v_t_thanh_home:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
]
