name: GitHub Actions zizmor

on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - ".github/workflows/**"
      - "action.yml"
      - "action.yaml"
  schedule:
    - cron: "30 2 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  zizmor:
    name: zizmor static analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # This security scan job requires write access in order to upload SARIF results and create issues for any detected vulnerabilities.
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482 #v0.6.4
        with:
          persona: pedantic
          advanced-security: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
